### ISSUE TITLE
db:seed aborted

### ISSUE THREAD

**Issue by kimchirice** [sheesh19/nautibnb#11]
➜  nautibnb git:(feature-reservation-cancel) rails db:migrate
➜  nautibnb git:(feature-reservation-cancel) ✗ rails db:seed
Clean database...
rails aborted!
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_1821a626a0" on table "yachts"
DETAIL:  Key (id)=(1) is still referenced from table "yachts".
: DELETE FROM "users" WHERE "users"."id" = $1
/Users/carmel/code/kimchirice/nautibnb/nautibnb/db/seeds.rb:11:in `<top (required)>'
/Users/carmel/code/kimchirice/nautibnb/nautibnb/bin/rails:9:in `<top (required)>'
/Users/carmel/code/kimchirice/nautibnb/nautibnb/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'

Caused by:
PG::ForeignKeyViolation: ERROR:  update or delete on table "users" violates foreign key constraint "fk_rails_1821a626a0" on table "yachts"
DETAIL:  Key (id)=(1) is still referenced from table "yachts".
/Users/carmel/code/kimchirice/nautibnb/nautibnb/db/seeds.rb:11:in `<top (required)>'
/Users/carmel/code/kimchirice/nautibnb/nautibnb/bin/rails:9:in `<top (required)>'
/Users/carmel/code/kimchirice/nautibnb/nautibnb/bin/spring:15:in `<top (required)>'
./bin/rails:3:in `load'
./bin/rails:3:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

**Comment by haokevinchen** [comment]
I believe this is because we didn't setup the destroy dependents. So we use the seed file, it is essentially destroying everything but the system is flagging that there's an user which has a yacht. I have a fix for this in my next push and pull request. Essentially I have re-orded the destroy_all methods from least dependent to most dependent. Seems to be working for me now.
